### ISSUE TITLE
Working batch examples for all existing models

### ISSUE THREAD

**Issue by ileppe** [neuropoly/qMRLab#121]
- [x] batch examples should be modular and consistent throughout
- [x] finish VFA_T1 see issue #116 
- [x] solution for uploading datasets #113 @jcohenadad
- [x] automatically generating batch examples #117 @agahkarakuzu
